### ISSUE TITLE
Your session has ended, please reconnect.

### ISSUE THREAD

**Issue by BramDecuypere** [benwinding/react-admin-firebase-demo-typescript#2]
Just did a fresh install and besides having to fix some issues in the node_modules, get this message after trying to login (I've created a fresh user in firebase)

`Your session has ended, please reconnect.`

Any ideas on how to fix this?

**Comment by BramDecuypere** [comment]
I closed this issue as I found out shortly after that my firebase rules were expired. 

On a fresh install and creation of the firebase app, this wouldn't have happened.

**Comment by benwinding** [comment]
Glad you got it sorted!

**Comment by simonngai** [comment]
I have the same issue when I write some security rules for firestore. It works fine and I can successfully login when I set all logged in users can read write (i.e. if request.auth != null)

The codes were to let users read/ write their own "clients". 

<img width="767" alt="Screenshot 2022-11-10 at 12 48 03 AM" src="https://user-images.githubusercontent.com/108149488/200890554-3333b6b9-5827-4046-970c-9ee85ffb784d.png">

After implementing the codes, I get logged out by React-admin automatically and shows the message "Your session has ended, please reconnect."

<img width="981" alt="Screenshot 2022-11-10 at 12 45 22 AM" src="https://user-images.githubusercontent.com/108149488/200890021-347526ff-cfab-4f75-8431-6ce65184164e.png">

<img width="987" alt="Screenshot 2022-11-10 at 1 18 16 AM" src="https://user-images.githubusercontent.com/108149488/200897373-66c50e6f-ed04-4844-9861-cfa70890b9aa.png">

I did test with firestore simulator and it works. I guess react-admin can list the clients? But how come I get logged off by react-admin? Even if react-admin gets no data, you can still log in, right? I am so confused. Hope anyone could help. Thanks.

<img width="837" alt="Screenshot 2022-11-10 at 12 51 09 AM" src="https://user-images.githubusercontent.com/108149488/200891898-fcec017b-4070-4ae3-bc7a-633198cd45e1.png">

**Comment by peter-wd-1** [comment]
Hi, @simonngai can I get a details of the app code?
